### ISSUE TITLE
Compilation failed on a ARM

### ISSUE THREAD

**Issue by wawax** [armadito/armadito-mod-pdf#7]
I tried to compiled the module on an ARM computer but it fails.
The error message is : 

make[1]: Entering directory '/root/src/armadito-mod-pdf/module'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"armadito-mod-modulePDF\" -DPACKAGE_TARNAME=\"armadito-mod-modulepdf\" -DPACKAGE_VERSION=\"0.9.0\" -DPACKAGE_STRING=\"armadito-mod-modulePDF\ 0.9.0\" -DPACKAGE_BUGREPORT=\"ufausther@teclib.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"armadito-mod-modulepdf\" -DVERSION=\"0.9.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DDEBUG=1 -I.    -I../lib/includes -I/usr/local/include   -g -MT modulePDF_la-modulePDF.lo -MD -MP -MF .deps/modulePDF_la-modulePDF.Tpo -c -o modulePDF_la-modulePDF.lo `test -f 'modulePDF.c' || echo './'`modulePDF.c
libtool: compile:  gcc -DPACKAGE_NAME=\"armadito-mod-modulePDF\" -DPACKAGE_TARNAME=\"armadito-mod-modulepdf\" -DPACKAGE_VERSION=\"0.9.0\" "-DPACKAGE_STRING=\"armadito-mod-modulePDF 0.9.0\"" -DPACKAGE_BUGREPORT=\"ufausther@teclib.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"armadito-mod-modulepdf\" -DVERSION=\"0.9.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DDEBUG=1 -I. -I../lib/includes -I/usr/local/include -g -MT modulePDF_la-modulePDF.lo -MD -MP -MF .deps/modulePDF_la-modulePDF.Tpo -c modulePDF.c  -fPIC -DPIC -o .libs/modulePDF_la-modulePDF.o
modulePDF.c: In function 'modulePDF_info':
modulePDF.c:47:6: error: 'struct a6o_module_info' has no member named 'update_date'
  info->update_date = os_strdup("2016-06-08T09:30:00Z");
      ^
modulePDF.c:50:6: error: 'struct a6o_module_info' has no member named 'timestamp'
  info->timestamp = ts;
      ^
modulePDF.c: In function 'modulePDF_scan':
modulePDF.c:63:25: warning: passing argument 2 of 'analyzePDF_ex' discards 'const' qualifier from pointer target type
  ret = analyzePDF_ex(fd,path);
                         ^
In file included from modulePDF.h:25:0,
                 from modulePDF.c:22:
../lib/includes/armaditopdf.h:75:5: note: expected 'char _' but argument is of type 'const char *'
 int analyzePDF_ex(int fd, char \* filename);
     ^
Makefile:492: recipe for target 'modulePDF_la-modulePDF.lo' failed
make[1]: *_\* [modulePDF_la-modulePDF.lo] Error 1
make[1]: Leaving directory '/root/src/armadito-mod-pdf/module'
Makefile:365: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by g-bougard** [comment]
This is a known issue as few recent updates in armadito-av libs made armadito-pdf incompatible.
We hope armadito-pdf will be updated soon to be compliant again.
